---
jobs:
- name: update-task-image
  serial: true
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: concourse-task-image-src
      trigger: true
  - task: docker-path
    file: pipeline-tasks/inflate.yml
    config:
      inputs:
        - name: concourse-task-image-src
        - name: pipeline-tasks
    params:
      INPUT_DIR: concourse-task-image-src/task
  - put: docker-image-repo
    params:
      build: inflate

resources:
- name: pipeline-tasks
  type: git
  source:
    uri: {{pipeline-tasks-git-url}}
    branch: {{pipeline-tasks-git-branch}}

- name: concourse-task-image-src
  type: git
  source:
    uri: {{concourse-task-image-git-url}}
    branch: {{concourse-task-image-git-branch}}

- name: docker-image-repo
  type: docker-image
  source:
    email: {{docker-email}}
    username: {{docker-username}}
    password: {{docker-password}}
    repository: {{docker-repository}}
