---
jobs:
- name: update-concourse-task-image
  plan:
  - get: concourse-images
    trigger: true
  - put: concourse-tasks-image-repo
    params:
      build: concourse-images/task/concourse-tasks
- name: update-sql-client-image
  plan:
  - get: concourse-images
    trigger: true
  - put: sql-image-repo
    params:
      build: concourse-images/task/sql-image
- name: update-oracle-image-task
  plan:
  - get: oracle-image-git-repository
    trigger: true
  - put: oracle-image-repository
    params:
      build: oracle-image-git-repository/OracleInstantClient/dockerfiles/19

resources:
- name: concourse-images
  type: git
  source:
    uri: {{concourse-task-image-git-url}}
    branch: {{concourse-task-image-git-branch}}

- name: sql-image-repo
  type: docker-image
  source:
    email: {{docker-email}}
    username: {{docker-username}}
    password: {{docker-password}}
    repository: {{sql-image-repository}}

- name: concourse-tasks-image-repo
  type: docker-image
  source:
    email: {{docker-email}}
    username: {{docker-username}}
    password: {{docker-password}}
    repository: {{concourse-tasks-repository}}

- name: oracle-image-git-repository
  type: git
  source:
    uri: {{oracle-image-git-repository}}
    branch: {{oracle-image-git-repository-branch}}

- name: oracle-image-repository
  type: docker-image
  source:
    email: {{docker-email}}
    username: {{docker-username}}
    password: {{docker-password}}
    repository: {{oracle-image-repository}}
