---
jobs:
- name: update-concourse-task-image
  plan:
  - get: concourse-images
    trigger: true
  - put: concourse-tasks-image-repo
    params:
      build: concourse-images/task/concourse-tasks
- name: update-sql-client-image
  plan:
  - get: concourse-images
    trigger: true
  - put: sql-image-repo
    params:
      build: concourse-images/task/sql-image

resources:
- name: concourse-images
  type: git
  source:
    uri: {{concourse-task-image-git-url}}
    branch: {{concourse-task-image-git-branch}}

- name: sql-image-repo
  type: docker-image
  source:
    email: {{docker-email}}
    username: {{docker-username}}
    password: {{docker-password}}
    repository: {{sql-image-repository}}

- name: concourse-tasks-image-repo
  type: docker-image
  source:
    email: {{docker-email}}
    username: {{docker-username}}
    password: {{docker-password}}
    repository: {{concourse-tasks-repository}}
