---
jobs:
- name: update-task-image
  serial: true
  plan:
  - get: concourse-task-image-src
    trigger: true
  - put: docker-image-repo
    params:
      build: concourse-task-image-src/task

resources:
- name: concourse-task-image-src
  type: git
  source:
    uri: {{concourse-task-image-git-url}}
    branch: {{concourse-task-image-git-branch}}

- name: docker-image-repo
  type: docker-image
  source:
    email: {{docker-email}}
    username: {{docker-username}}
    password: {{docker-password}}
    repository: {{docker-repository}}
