---
jobs:
- name: update-concourse-task-image
  serial: true
  plan:
  - get: concourse-task-image-src
    trigger: true
  - put: docker-image-repo
    params:
      build: concourse-task-image-src/task/concourse-tasks
- name: update-sql-image-task
  plan:
  - get: concourse-task-image-src
    trigger: true
  - put: docker-image-repo
    params:
      build: concourse-task-image-src/task/sql-image

resources:
- name: concourse-task-image-src
  type: git
  source:
    uri: {{concourse-task-image-git-url}}
    branch: {{concourse-task-image-git-branch}}

- name: sql-image-repo
  type: docker-image
  source:
    email: {{docker-email}}
    username: {{docker-username}}
    password: {{docker-password}}
    repository: {{sql-image-repository}}

- name: concourse-tasks-repo
  type: docker-image
  source:
    email: {{docker-email}}
    username: {{docker-username}}
    password: {{docker-password}}
    repository: {{concourse-tasks-repository}}
